title: Lerntagebuch Modul «Bibliotheks- und Archivinformatik»
author: Patricia
email: patricia.schneider@stud.fhgr.ch
description: > # this means to ignore newlines
  Schön, dass Du da bist. Ich schreibe hier über meine Erkenntnisse und Erfahrungen im Modul «Bibliotheks- und Archivinformatik» an der Fachhochschule Graubünden.

# social links
github_username:  patriciaschneiderFHGR # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
